name: Build Android APK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Display Java version
        run: java -version
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew :androidApp:assembleRelease :androidApp:bundleRelease --info
      - name: List files
        run: ls -lah androidApp/build/outputs/apk/release
      - name: Sign APK
        uses: ./.github/actions/sign-android-release
        with:
          releaseDirectory: androidApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 35.0.0
      - name: Sign Bundle
        uses: ./.github/actions/sign-android-release
        with:
          releaseDirectory: androidApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 35.0.0
      - name: Move artifact
        run: |
          mv androidApp/build/outputs/apk/release/androidApp-release-unsigned-signed.apk kaesekaestchen.apk
          mv androidApp/build/outputs/bundle/release/androidApp-release.aab kaesekaestchen.aab
      - name: List files
        run: find .
      - name: Upload kaesekaestchen.apk & kaesekaestchen.aab
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: android
          path: |
            kaesekaestchen.apk
            kaesekaestchen.aab
